class Garumu extends Chara{
	static getText(){
		//キャラ説明
		return "アタックタイプ：<br>素早く動いて手数で相手を攻める";
	}
	constructor(aX,aY,aTeam,aOperationNum){
		let tData=Garumu.getCharaData();
		super(aX,aY,aTeam,tData,aOperationNum);
		this.data=tData;

		this.doubleTurnFlag=false;
		this.additionalDelayTemp=0;
	}
	static getCharaNatureSkill(){
		//特性の説明
		return "1ターンに2回行動できる";
	}
	static getCharaData(){
		return {NAME:"ガルム",
						HP:80,
						MP:5,
						ATK:23,
						DEF:21,
						SPD:26,
						MOV:2,
						TYPE:"diamond",
						IMAGE:1264010001,
						DECK:Garumu.getDeck()
		}
	}
	static getDeck(){
		return [
			{NUMBER:101,
				TEXT:"隣のマスに威力3のダメージ",
				RANGE:[["distance",1]],
				POWER:3,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:102,
				TEXT:"隣のマスに威力3のダメージ",
				RANGE:[["distance",1]],
				POWER:3,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:103,
				TEXT:"隣のマスに威力3のダメージ",
				RANGE:[["distance",1]],
				POWER:3,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:104,
				TEXT:"2マス隣に威力2ダメージ",
				RANGE:[["distance",2]],
				POWER:2,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:105,
				TEXT:"2マス隣に威力2のダメージ",
				RANGE:[["distance",2]],
				POWER:2,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:105,
				TEXT:"2マス隣に威力2のダメージ",
				RANGE:[["distance",2]],
				POWER:2,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:7,
				TEXT:"シャッフルしてもう一度行動",
				RANGE:[],
				POWER:0,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[{effect:"getTurn"}],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[{effect:"shuffle"}],
				M_ATTACK:0,
				F_ATTACK:false,
				E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:108,
				TEXT:"相手全体に威力1のダメージ",
				RANGE:[["enemy"]],
				POWER:1,
				DELAY:5,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[5]
			},
			{NUMBER:106,
				TEXT:"十字に威力２ダメージ",
				RANGE:[["vertical",1],["horizontal",1]],
				POWER:2,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:106,
				TEXT:"十字に威力２ダメージ",
				RANGE:[["vertical",1],["horizontal",1]],
				POWER:2,
				DELAY:0,
				MAGIC:0,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:111,
				TEXT:"周囲１２マスに敵味方無視の威力4のダメージ",
				RANGE:[["circumference",2]],
				POWER:4,
				DELAY:0,
				MAGIC:1,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:2,
				F_ATTACK:true,
		    E_ATTACK:true,
				ANIMATION:[0,3]
			},
			{NUMBER:112,
				TEXT:"周囲１２マスに敵味方無視の威力4のダメージ",
				RANGE:[["circumference",2]],
				POWER:4,
				DELAY:0,
				MAGIC:1,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:2,
				F_ATTACK:true,
		    E_ATTACK:true,
				ANIMATION:[0,3]
			},
			{NUMBER:613,
				TEXT:"スピード6アップ　その後DELAYを50下げる（タイプ一致時8アップ）",
				RANGE:[],
				POWER:0,
				DELAY:0,
				MAGIC:2,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[{effect:"spd",value:6,additionOfMatchingType:2},{effect:"delay",value:-50}],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:114,
				TEXT:"相手全体に威力3のダメージを与え,自分のDELAYを100下げる その後シャッフル",
				RANGE:[["enemy"]],
				POWER:3,
				DELAY:0,
				MAGIC:3,
				SUPPORT_Be_Myself:[],
				SUPPORT_Af_Myself:[{effect:"delay",value:-100}],
				SUPPORT_Be_Enemy:[],
				SUPPORT_Af_Enemy:[],
				SUPPORT_Otherwise:[{effect:"revers"},{effect:"shuffle"}],
				M_ATTACK:0,
				F_ATTACK:false,
		    E_ATTACK:true,
				ANIMATION:[0]
			},
			{NUMBER:0,
					TEXT:"スカ　何も起こらない",
					RANGE:[],
					POWER:0,
					DELAY:0,
					MAGIC:0,
					SUPPORT_Be_Myself:[],
					SUPPORT_Af_Myself:[],
					SUPPORT_Be_Enemy:[],
					SUPPORT_Af_Enemy:[],
					SUPPORT_Otherwise:[{effect:"revers"}],
					M_ATTACK:0,
					F_ATTACK:false,
			    E_ATTACK:true,
					ANIMATION:[0]
				},]
	}
	startTurn(){
		if(this.doubleTurnFlag){
			this.getTurnFlag=true;
		}
		return super.startTurn();
	}
	endTurn(aDelay){
		if(this.getTurnFlag){
			return super.endTurn(0);
		}
		else{
			if(this.doubleTurnFlag){
				let tDelay=this.additionalDelayTemp;
				this.additionalDelayTemp=0;
				this.doubleTurnFlag=false;
				return super.endTurn(tDelay);
			}
			else{
				this.additionalDelayTemp+=aDelay;
				this.doubleTurnFlag=true;
				newLog([mTurnChara,"は特性によって連続で行動"])
				return new Promise((res,rej)=>{res();});
			}
		}
	}
}
